version: '3'

volumes:
  porovnavac_local_postgres_data: {}
  porovnavac_local_postgres_data_backups: {}
  porovnavac_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: porovnavac_local_django
    container_name: porovnavac_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
      - porovnavac_media:/app/porovnavac/porovnavac/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: porovnavac_production_postgres
    container_name: porovnavac_local_postgres
    volumes:
      - porovnavac_local_postgres_data:/var/lib/postgresql/data
      - porovnavac_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: porovnavac_local_docs
    container_name: porovnavac_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./porovnavac:/app/porovnavac:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: porovnavac_local_redis

  celeryworker:
    <<: *django
    image: porovnavac_local_celeryworker
    container_name: porovnavac_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: porovnavac_local_celerybeat
    container_name: porovnavac_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: porovnavac_local_flower
    container_name: porovnavac_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
