# Generated by Django 4.0.8 on 2023-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_pictures/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website_icons/'),
        ),
    ]
